First lab
PreFX48/renju pull request #2
Opened 2016-11-23 18:20 UTC by PreFX48

2016-11-25 20:52 UTC, gamers5a commented on lab_solution.py
> +plt.show()
Можно использовать %matplotlib inline

2016-11-25 20:59 UTC, gamers5a commented on lab_solution.py
> +    return np.linalg.pinv((samples_t @ samples)) @ samples_t @ labels
Кажется, псевдообратную матрицу нужно было сделать ручками, но не суть важно.

2016-11-25 21:02 UTC, gamers5a commented on lab_solution.py
> +plt.scatter(samples_x[:, 0], samples_x[:, 1], c='b', marker='.', s=50, edgecolors='none', alpha=0.7)
Edgecolors=None задано в функции по умолчанию, зачем еще раз передавать дефолт?

2016-11-25 21:05 UTC, gamers5a commented on lab_solution.py
> +plt.show()
Может быть, сдвинув легенду в левый нижний угол, было бы чуть лучше видно?

2016-11-25 21:16 UTC, gamers5a commented on lab_solution.py
> +    current_location = np.asarray(start, dtype='float64')[np.newaxis].transpose().copy()
Не очень понятно, зачем нужны `copy`, если сильно нужны, можно было передать как параметр в `np.array`, получается 2 раза вызов одинакового метода.

2016-11-25 21:18 UTC, gamers5a commented on lab_solution.py
> +    return subsets
2 раза хранить одни и те же данные? Кажется, генераторы на лету были бы менее беспощадны к оперативке.

2016-11-25 21:19 UTC, alex-kharlamov commented on lab_solution.py
> +data = genfromtxt('train.csv', delimiter=',')[1:]
Есть сильно более быстрая и удобная альтернатива в виде `pandas.read_csv`

2016-11-25 21:23 UTC, gamers5a commented on lab_solution.py
> +    if size == 300:
Что это, зачем это? 300? Почему 300? А другие размеры?

2016-11-25 21:31 UTC, alex-kharlamov requested changes
First review before merging.

2016-11-26 17:41 UTC, PreFX48 commented on lab_solution.py
> +    return np.linalg.pinv((samples_t @ samples)) @ samples_t @ labels
Ну, это что-то из категории самостоятельного написания матричного умножения и т.д. - numpy есть, вот нам и счастье

2016-11-26 17:42 UTC, PreFX48 commented on lab_solution.py
> +plt.show()
Какова выгода?

2016-11-26 17:45 UTC, PreFX48 commented on lab_solution.py
> +plt.scatter(samples_x[:, 0], samples_x[:, 1], c='b', marker='.', s=50, edgecolors='none', alpha=0.7)
У функции plot задано, у функции scatter - нет, по умолчанию рисует границы

2016-11-26 17:47 UTC, PreFX48 commented on lab_solution.py
> +plt.show()
В левый нижний - нет. Но в правый верхний, пожалуй, да. Сделаю

2016-11-26 17:59 UTC, PreFX48 commented on lab_solution.py
> +    current_location = np.asarray(start, dtype='float64')[np.newaxis].transpose().copy()
Подправлю

2016-11-26 18:05 UTC, PreFX48 commented on lab_solution.py
> +    return subsets
Будут тебе генераторы :)

2016-11-26 18:05 UTC, PreFX48 commented on lab_solution.py
> +data = genfromtxt('train.csv', delimiter=',')[1:]
Гляну

2016-11-26 19:07 UTC, gamers5a commented on lab_solution.py
> +plt.show()
Не нужно каждый раз писать `plt.show`

2016-11-26 19:09 UTC, gamers5a commented on lab_solution.py
> +plt.scatter(samples_x[:, 0], samples_x[:, 1], c='b', marker='.', s=50, edgecolors='none', alpha=0.7)
![image](https://cloud.githubusercontent.com/assets/2713468/20642635/df633242-b424-11e6-94df-5bf079e72136.png)
![image](https://cloud.githubusercontent.com/assets/2713468/20642638/eed4c948-b424-11e6-97fe-2b5a0445a031.png)
Все-таки задано.

2016-11-26 19:40 UTC, PreFX48 commented on lab_solution.py
> +    if size == 300:
Мда, сильно извиняюсь за <нехорошее слово>код. Вообще это далее используется для подсчёта экспоненциального сглаживания.
300 выбрано просто как значение "ни туда, ни сюда". Для каждого размера батча тестировать это смысла нет, потому что тренд, как было мною проверено, одинаковый для всех размеров батчей, так что смысла тестировать на них особо нет.

2016-11-26 19:41 UTC, PreFX48 commented on lab_solution.py
> +plt.show()
Ну такое...
Предпочитаю иметь более прямой контроль над выводом.

2016-11-26 19:43 UTC, PreFX48 commented on lab_solution.py
> +plt.scatter(samples_x[:, 0], samples_x[:, 1], c='b', marker='.', s=50, edgecolors='none', alpha=0.7)
None != 'none'
None - значение по умолчанию (patch.edgecolor)
'none' - отсутствие границы

2016-11-26 20:15 UTC, gamers5a commented on lab_solution.py
> +plt.scatter(samples_x[:, 0], samples_x[:, 1], c='b', marker='.', s=50, edgecolors='none', alpha=0.7)
хм, постиг, тогда извиняюсь.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +    return np.linalg.pinv((samples_t @ samples)) @ samples_t @ labels
Думаю, что достаточно `np.linalg.pinv((samples)) @ labels`, а теперь надо понятно, почему разделение было правильное ;)

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +x1_t = x1.reshape((x1.shape[0], 1))
Перемудрил ты тут немного, зачем-то в начале расщепил на два вектора, потом столько возни.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +def classify(x, coefs, shift):
Там все это прекрасно пишется через матричные выражения ;)

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +x = [x for x in range(-4, 9)]
Для фиксации прямой достаточно двух точек.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +    if points_log != None:
можно просто писать `if points_log:`

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +    return current_location
логирование лучше так же через return передавать, в питоне принято возвращать tuple-ы.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +def quadratic_descent_1d(samples, labels, start, direction, step=0.01):
Название так себе, да и лучше бы learning_rate возвращать

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +        yield ((shuffled_samples[i*subset_size:(i+1)*subset_size],
зачем столько скобок? кажется, хвост ты теряешь..

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +test_labels = (test_labels - 0.5) * 2
Опасна штука. Там может не чистые +1/-1 получится.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +    if size == 300:
Огромный нечитаемый блок кода :(

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +loss_coefs = [x/10 for x in range(1, 10)]
для этого есть функция в numpy

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +losses = [[] for i in range(9)]
`losses = [[]]*9` а еще лучш все через константы провязывать

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +sizes = [5, 10, 25, 50, 100, 200, 300, 400, 500, 600, 700, 800]
размер чего?

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +            loss.append(logistic_loss(prepared_samples, labels, current_weights))
везде ж одинаковые значения, зачем каждый раз считать?

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +            current_weights = gradient_descent(subset[0], subset[1], current_weights,
там слишко большая логика внутри накручена, надо попроще функцию использовать

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +            current_weights = gradient_descent(subset[0], subset[1], current_weights,
лучше писать так

```
result = function(
    arg1 = val1,
    arg2 = val2,
    ...
)
```

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +                    loss.append(loss_coef * loss[-1] + (1 - loss_coef) * logistic_loss(subset[0], subset[1], current_weights))
И здесь такое же замечание.

2017-03-16 20:07 UTC, dasimagin commented on lab_solution.py
> +        if math.sqrt(np.dot(old_weights - current_weights, old_weights - current_weights)) < 1e-4:
я думаю в numpy есть евклидова метрика.

2017-03-16 20:29 UTC, PreFX48 commented on lab_solution.py
> +test_labels = (test_labels - 0.5) * 2
Да вроде не должно. Дробная часть у нас тут является отрицательной степенью двойки, так что стандартные флоаты с этим без округления работают

2017-03-16 20:54 UTC, merged